---
title: Computer Science Intvents Wavelets
author: Matthew Avery
date: '2019-11-15'
slug: computer-science-intvents-wavelets
categories:
  - ML Invents
tags: []
description: ''
thumbnail: ''
---

A friend of mine shared an abstract with me from an upcoming talk by Computer Science professor:

> Data analysis is an emerging research topic that focuses on understanding patterns of data to discover knowledge. For understanding the data, various machine learning (ML) techniques are commonly utilized to build learning models. For maintaining high performance of the models, it is important to extract good features and utilize them to build a reliable learning model. Since the aim of the feature extraction is finding lower-dimensional feature space that contains meaningful information by removing redundant and irrelevant information, it is necessary to be performed in analyzing data. However, the importance of applying feature extraction has not been emphasized fully in data analysis. Instead, many studies mainly focused on finding techniques that produce better performances in classifying data. We mainly emphasize feature extraction as an essential task in understanding data. For extracting features from data, we considered utilizing wavelet transformation because it is good for analyzing data contains rapid changes and trends. It also reduces computational complexity when analyzing large-scale data. For showing the effectiveness of utilizing the wavelet-based analysis, the approach was tested in different application domains as identifying abnormal activities in network traffic data, classifying human emotions in song and speech data, and detecting the level of bleeding from hemorrhage shock data. In addition, utilization of visualization has been performed to show the effectiveness of the technique in understanding data.

Modern statistics <a href = "https://en.wikipedia.org/wiki/History_of_statistics#Development_of_modern_statistics">has been around longer than computers</a>, so I don't think "emerging field" is quite right. And "feature extraction" (the term the Machine Learning community invented to mean "model selection") was emphasized in just about every class I took in grad school. 

I am glad that the ML folks have discovered that wavelets are a useful tool for this. Only about <a href = "https://web.stanford.edu/~hastie/Papers/ESLII.pdf">two decades late</a>! :-D (See Chapter 5!)